# Open Data Contract Standard (ODCS) v3.1.0 — generert fra datamodellen.
apiVersion: v3.1.0
kind: DataContract
id: urn:odcs:dyrkbar-jord-ny-datakilde:1.0.0
version: 1.0.0
status: active
name: Dyrkbar jord - Ny datakilde
schema:
- name: arealressursflate
  physicalName: arealressursflate
  logicalType: object
  physicalType: table
  description: "et sammenhengende areal som er tilordnet de samme egenskapsverdiene\
    \ i henhold til et arealressursklassifikasjonssystem\r\n-- Definition -- \r\n\
    a continuous area which has been assigned the same attribute values in accordance\
    \ with an area resource classification system"
  customProperties:
  - property: sosiObjektType
    value: arealressursflate
  - property: defaultCrs
    value: EPSG:25833
  properties:
  - name: geometri
    logicalType: object
    physicalType: geometry(Polygon,25833)
    required: true
    customProperties:
    - property: geometryType
      value: Polygon
    - property: crs
      value: EPSG:25833
  - name: id
    logicalType: integer
    required: true
    primaryKey: true
  - name: identifikasjon.lokalid
    logicalType: string
    required: true
  - name: identifikasjon.navnerom
    logicalType: string
    required: true
  - name: informasjon
    logicalType: string
    required: true
  - name: kopidata.kopidato
    logicalType: timestamp
  - name: kopidata.områdeid
    logicalType: integer
  - name: kopidata.originaldatavert
    logicalType: string
  - name: dyrkbarjord
    logicalType: string
    required: true
  - name: fulldyrka2008
    logicalType: string
    required: true
  - name: myrtorv
    logicalType: string
    required: true
  - name: planeringsjord
    logicalType: string
    required: true
  - name: verneform
    logicalType: string
    required: true
  - name: årsversjon
    logicalType: integer
    required: true
  - name: avgrensesavarealressursgrense_1
    logicalType: string
  - name: avgrensesavarealressursgrense_2
    logicalType: string
  - name: avgrensesavarealressursgrense_3
    logicalType: string
- name: arealressursgrense
  physicalName: arealressursgrense
  logicalType: object
  physicalType: table
  description: "avgrensing for en eller to arealressursflater\r\n-- Definition --\
    \ \r\ndelimitation for one or two area resource surfaces"
  customProperties:
  - property: sosiObjektType
    value: arealressursgrense
  - property: defaultCrs
    value: EPSG:25833
  properties:
  - name: geometri
    logicalType: object
    physicalType: geometry(LineString,25833)
    required: true
    customProperties:
    - property: geometryType
      value: LineString
    - property: crs
      value: EPSG:25833
  - name: id
    logicalType: integer
    required: true
    primaryKey: true
