@startuml
title Tilfluktsrom - Offentlige - Datamodell for hendelser - Objekttyper

skinparam backgroundColor #F5F5F5
skinparam shadowing false
skinparam RoundCorner 6
skinparam ArrowColor #6C8198
skinparam class {
  BackgroundColor #FBF2E8
  BorderColor #9C8578
  FontColor #2D201A
  HeaderBackgroundColor #EFE1D6
  HeaderFontColor #2D201A
  AttributeIconSize 0
}
skinparam note {
  BackgroundColor #FFFFFF
  BorderColor #6C8198
  FontColor #2D201A
}
skinparam stereotypeCBackgroundColor #EAD9CE
skinparam stereotypeCBorderColor #9C8578
skinparam stereotypeCFontColor #2D201A

package "Objekttyper" {

  abstract class VersjonertObjekt <<featureType>> {
    + identifikasjon [1] : Identifikasjon
    + registreringstidspunkt [1] : Date
    + oppdateringstidspunkt [0..1] : Date
    + gyldigFra [0..1] : Date
    + gyldigTil [0..1] : Date
  }

  abstract class Fellesegenskaper <<featureType>> {
    + kommentar [0..1] : CharacterString
    + geometriobjekt [0..1] : URI
  }

  class ops <<featureType>> {
    ' Ingen attributter
  }

  class Helsesamvirke <<featureType>> {
    + samvirkeType [1] : TypeHelsesamvirke
  }

  abstract class Hendelse <<featureType>> {
    + punkt [1] : Punkt
    + betegnelse [0..1] : CharacterString
    + opphavsaktør [1] : Hovedaktør
    + beskrivelse [0..1] : CharacterString
    + prioritet [1] : PrioritetHendelse
    + kompleksitet [1] : Kompleksitet
    + aktørPerspektiv [1..*] : AktørPerspektiv
    + lokalitetstype [1] : Lokalitetstype
    + øvelse [1] : Boolean
  }

  class PlanlagtHendelse <<featureType>> {
    + planlagtHendelsesType [1] : TypePlanlagtHendelse
  }

  class FramskrevetSkadested <<featureType>> {
    + sted [1] : GM_Object
    + typeSkadested [0..1] : TypeSkadested
    + beskrivelse [0..1] : CharacterString
    + estimertTidspunkt [0..1] : Date
  }

  class SammensattHendelse <<featureType>> {
    ' Ingen attributter
  }

  class AnnenHendelse <<featureType>> {
    ' Ingen attributter
  }

  class Sikkerhetshendelse <<featureType>> {
    + sikkerhetshendelseType [1] : TypeSikkerhetshendelse
  }

  class "FramskrevetHendelsesområde" as FramskrevetHendelsesomr_de <<featureType>> {
    + flate [1] : GM_Surface
    + beskrivelse [0..1] : CharacterString
    + estimertTidspunkt [0..1] : Date
  }

  class Naturhendelse <<featureType>> {
    + naturhendelseType [1] : TypeNaturhendelse
  }

  class Ulykke <<featureType>> {
    + ulykkeType [1] : TypeUlykke
  }

  class "Hendelsesområde" as Hendelsesomr_de <<featureType>> {
    + flate [1] : GM_Surface
    + beskrivelse [0..1] : CharacterString
  }

  class "FramskrevetInnsatsområde" as FramskrevetInnsatsomr_de <<featureType>> {
    + flate [1] : GM_Surface
    + beskrivelse [0..1] : CharacterString
    + estimertTidspunkt [0..1] : Date
  }

  class "Innsatsområde" as Innsatsomr_de <<featureType>> {
    + flate [1] : GM_Surface
    + beskrivelse [0..1] : CharacterString
  }

  class Skadested <<featureType>> {
    + sted [1] : GM_Object
    + typeSkadested [0..1] : TypeSkadested
    + beskrivelse [0..1] : CharacterString
  }

  class Objekt <<featureType>> {
    + typeObjekt [1] : TypeObject
    + posisjon [1] : GM_Object
    + posisjonskvalitet [1] : Posisjonskvalitet
  }

  class "Observatør" as Observat_r <<featureType>> {
    + kontaktinformasjon [1] : CharacterStreng
    + OPSoperatør [1] : Boolean
    + sensor [1] : Boolean
    + virksomhet [0..1] : CharacterStreng
  }

  class Observasjon <<featureType>> {
    + observasjonsmåte [1] : Observasjonsmåte
    + observasjonskvalitet [0..1] : Observasjonskvalitet
    + observasjonFraTid [1] : Date
    + observasjonTilTid [1] : Date
    + objektPosisjon [0..1] : GM_Objekt
    + observertFraPosisjon [1] : GM_Object
    + posisjonskvalitet [0..1] : Posisjonskvalitet
  }

  abstract class Ressurs <<featureType>> {
    + posisjon [1] : Punkt
    + aktør [1] : Aktør
    + ressursID [1] : CharacterString
    + estimertAnkomsttid [0..1] : Date
    + tilgjengelighetOps [1] : TilgjengelighetOps
    + tilgjengelighetHendelse [1] : TilgjengelighetHendelse
    + utstyr [0..*] : TypeUtstyr
  }

  class Drone <<featureType>> {
    + synsfelt [0..1] : Flate
    + dronetype [1] : TypeDrone
  }

  class Depot <<featureType>> {
    ' Ingen attributter
  }

  class AnnenRessurs <<featureType>> {
    + type [1] : TypeAnnenRessurs
  }

  class Transportmiddel <<featureType>> {
    + type [1] : TypeTransportmiddel
    + rolle [1] : TypeRolle
  }

  class Personell <<featureType>> {
    + rolle [0..1] : TypeRolle
    + typeEkspert [0..1] : TypeEkspert
  }

  class Tiltakslokasjon <<featureType>> {
    + posisjon [1] : CharacterString
    + type [1] : TypeTiltakslokasjon
    + aktør [1] : Aktør
    + status [1] : Status
    + prioritetTilak [1] : Integer
    + typeFaresone [0..1] : TypeFaresone
    + typeRute [0..1] : TypeRute
    + bevarÅsted [0..1] : Boolean
  }

  class Kontekst <<featureType>> {
    + type [1] : TypeKontekst
    + aktør [1] : Aktør
    + posisjon [1] : GM_Object
  }

  class Identifikasjon <<dataType>> {
    + lokalId [1] : uuid
    + navnerom [1] : CharacterString
    + versjonId [0..1] : CharacterString
  }

  class "AktørPerspektiv" as Akt_rPerspektiv <<dataType>> {
    + aktør [1] : Hovedaktør
    + prioritet [1] : PrioritetHendelse
    + kompleksitet [0..1] : Kompleksitet
  }

  class X___TiltakOppgave {
  }
}

  VersjonertObjekt <|-- Fellesegenskaper
  ops --> Hendelse : hendelse [0..*]
  ops --> Ressurs : potesiellResserus [0..*]
  Hendelse <|-- Helsesamvirke
  Fellesegenskaper <|-- Hendelse
  Hendelse --> ops : ops [1]
  Hendelse --> Objekt : objekt [1..*]
  Hendelse --> FramskrevetSkadested : utbredelse [0..*]
  Hendelse --> Tiltakslokasjon : tiltakslokasjon [0..*]
  Hendelse --> Skadested : skadested [0..*]
  Hendelse --> Hendelsesomr_de : hendelsesområde [0..*]
  Hendelse --> SammensattHendelse : sammensattHendelse [0..*]
  Hendelse --> Ressurs : tilordnetRessurs [0..*]
  Hendelse --> Kontekst : kontekst [0..*]
  Hendelse --> Innsatsomr_de : innsatsområde [0..*]
  Hendelse --> Observasjon : ____innmeldtObservasjon [1]
  Hendelse --> Observat_r : innmelder [1..*]
  Hendelse <|-- PlanlagtHendelse
  Fellesegenskaper <|-- FramskrevetSkadested
  Fellesegenskaper <|-- SammensattHendelse
  SammensattHendelse --> Hendelse : hendelse [0..*]
  Hendelse <|-- AnnenHendelse
  Hendelse <|-- Sikkerhetshendelse
  Fellesegenskaper <|-- FramskrevetHendelsesomr_de
  Hendelse <|-- Naturhendelse
  Hendelse <|-- Ulykke
  Fellesegenskaper <|-- Hendelsesomr_de
  Hendelsesomr_de --> FramskrevetHendelsesomr_de : scenario [0..*]
  Fellesegenskaper <|-- FramskrevetInnsatsomr_de
  Fellesegenskaper <|-- Innsatsomr_de
  Innsatsomr_de --> FramskrevetInnsatsomr_de : scenario [0..*]
  Fellesegenskaper <|-- Skadested
  Skadested --> FramskrevetSkadested : framskriving [0..*]
  Fellesegenskaper <|-- Objekt
  Objekt --> Observasjon : observasjon [1..*]
  VersjonertObjekt <|-- Observat_r
  Fellesegenskaper <|-- Observat_r
  Fellesegenskaper <|-- Observasjon
  Observasjon --> Objekt : objekt [1..*]
  Observasjon --> Observat_r : observatør [1]
  Observasjon --> Observat_r : observatør [0..1]
  Observasjon --> Ressurs : observertAv [0..1]
  Fellesegenskaper <|-- Ressurs
  Ressurs --> Hendelse : hendelse [0..1]
  Ressurs --> Tiltakslokasjon : [0..*]
  Ressurs <|-- Drone
  Drone --> Personell : droneoperatør [0..1]
  Ressurs <|-- Depot
  Ressurs <|-- AnnenRessurs
  Ressurs <|-- Transportmiddel
  Ressurs <|-- Personell
  Personell --> Transportmiddel : transportmiddel [0..1]
  Fellesegenskaper <|-- Tiltakslokasjon
  Tiltakslokasjon --> Ressurs
  Tiltakslokasjon --> X___TiltakOppgave
  Fellesegenskaper <|-- Kontekst

@enduml
