<?xml version="1.0" encoding="UTF-8"?><schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:filleveranser="https://skjema.geonorge.no/SOSI/produktspesifikasjon/jordressurs/filleveranser/1.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo" elementFormDefault="qualified" targetNamespace="https://skjema.geonorge.no/SOSI/produktspesifikasjon/jordressurs/filleveranser/1.0" version="1.0">
  <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo" schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
  <import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
  <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
  <simpleType name="HellingGjsnittType">
    <union memberTypes="filleveranser:HellingGjsnittEnumerationType filleveranser:HellingGjsnittOtherType"/>
  </simpleType>
  <simpleType name="HellingGjsnittEnumerationType">
    <restriction base="string">
      <enumeration value="0 - 25 %"/>
      <enumeration value="≥ 25 - 33 %"/>
      <enumeration value="≥ 33 %"/>
    </restriction>
  </simpleType>
  <simpleType name="HellingGjsnittOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
  <element name="Identifikasjon" substitutionGroup="gml:AbstractObject" type="filleveranser:IdentifikasjonType"/>
  <complexType name="IdentifikasjonType">
    <sequence>
      <element name="lokalId" type="string">
        <annotation>
          <appinfo>
            <sc:taggedValue tag="SOSI_navn">LOKALID</sc:taggedValue>
          </appinfo>
        </annotation>
      </element>
      <element name="navnerom" type="string">
        <annotation>
          <appinfo>
            <sc:taggedValue tag="SOSI_navn">NAVNEROM</sc:taggedValue>
          </appinfo>
        </annotation>
      </element>
      <element minOccurs="0" name="versjonId" type="string">
        <annotation>
          <appinfo>
            <sc:taggedValue tag="SOSI_navn">VERSJONID</sc:taggedValue>
          </appinfo>
        </annotation>
      </element>
    </sequence>
  </complexType>
  <complexType name="IdentifikasjonPropertyType">
    <sequence>
      <element ref="filleveranser:Identifikasjon"/>
    </sequence>
  </complexType>
  <element name="JordressursGrense" substitutionGroup="gml:AbstractFeature" type="filleveranser:JordressursGrenseType"/>
  <complexType name="JordressursGrenseType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element name="grense" type="gml:CurvePropertyType">
            <annotation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">GM_Curve</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="JordressursGrensePropertyType">
    <sequence minOccurs="0">
      <element ref="filleveranser:JordressursGrense"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="Jordressurser" substitutionGroup="filleveranser:Jordressurser_Fellesgenskaper" type="filleveranser:JordressurserType"/>
  <complexType name="JordressurserType">
    <complexContent>
      <extension base="filleveranser:Jordressurser_FellesgenskaperType">
        <sequence>
          <element name="område" type="gml:SurfacePropertyType">
            <annotation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">FLATE</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="jordressursklasse" type="filleveranser:JordressursklasserType">
            <annotation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">JRKLASSER</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="hellingGjsnitt" type="filleveranser:HellingGjsnittType">
            <annotation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">HELLINGGJSNITT</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="steinblokk" type="filleveranser:SteinBlokkType">
            <annotation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">STEINBLOKK</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="årsakTilNedklassifisering" type="filleveranser:ÅrsakTilNedklassifiseringType"/>
          <element name="tilleggsinformasjon" type="filleveranser:TilleggsinformasjonType">
            <annotation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">TILLEGG</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="kartleggingsår" type="integer">
            <annotation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">KL_ÅR</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="kartleggingsmetodikk" type="filleveranser:KartleggingsmetodikkType">
            <annotation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">KL_METODIKK</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="opprinneligLokalId" type="integer">
            <annotation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">FIGURID</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element maxOccurs="unbounded" minOccurs="0" name="avgrensesAvJordressursgrense" type="filleveranser:JordressursGrensePropertyType"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="JordressurserPropertyType">
    <sequence minOccurs="0">
      <element ref="filleveranser:Jordressurser"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="Jordressurser_Fellesgenskaper" substitutionGroup="gml:AbstractFeature" type="filleveranser:Jordressurser_FellesgenskaperType"/>
  <complexType name="Jordressurser_FellesgenskaperType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element name="identifikasjon" type="filleveranser:IdentifikasjonPropertyType">
            <annotation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">IDENT</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="kopidata" type="filleveranser:KopidataPropertyType">
            <annotation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">KOPIDATA</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element minOccurs="0" name="kvalitet" type="filleveranser:PosisjonskvalitetPropertyType">
            <annotation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">KVALITET</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="verifiseringsdato" type="date">
            <annotation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">VERIFISERINGSDATO</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="Jordressurser_FellesgenskaperPropertyType">
    <sequence minOccurs="0">
      <element ref="filleveranser:Jordressurser_Fellesgenskaper"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <simpleType name="JordressursklasserType">
    <union memberTypes="filleveranser:JordressursklasserEnumerationType filleveranser:JordressursklasserOtherType"/>
  </simpleType>
  <simpleType name="JordressursklasserEnumerationType">
    <restriction base="string">
      <enumeration value="Svært gode jordressuser"/>
      <enumeration value="Gode jordressurser"/>
      <enumeration value="Middels gode jordressurser"/>
      <enumeration value="Mindre gode jordressurser"/>
    </restriction>
  </simpleType>
  <simpleType name="JordressursklasserOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
  <simpleType name="KartleggingsmetodikkType">
    <union memberTypes="filleveranser:KartleggingsmetodikkEnumerationType filleveranser:KartleggingsmetodikkOtherType"/>
  </simpleType>
  <simpleType name="KartleggingsmetodikkEnumerationType">
    <restriction base="string">
      <enumeration value="Detaljert kartlegging"/>
      <enumeration value="Forenklet kartlegging"/>
      <enumeration value="Harmonisert kartlegging"/>
    </restriction>
  </simpleType>
  <simpleType name="KartleggingsmetodikkOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
  <element name="Kopidata" substitutionGroup="gml:AbstractObject" type="filleveranser:KopidataType"/>
  <complexType name="KopidataType">
    <sequence>
      <element name="områdeId" type="integer">
        <annotation>
          <appinfo>
            <sc:taggedValue tag="SOSI_navn">OMRÅDEID</sc:taggedValue>
          </appinfo>
        </annotation>
      </element>
      <element name="originalDatavert" type="string">
        <annotation>
          <appinfo>
            <sc:taggedValue tag="SOSI_navn">ORIGINALDATAVERT</sc:taggedValue>
          </appinfo>
        </annotation>
      </element>
      <element name="kopidato" type="date">
        <annotation>
          <appinfo>
            <sc:taggedValue tag="SOSI_navn">KOPIDATO</sc:taggedValue>
          </appinfo>
        </annotation>
      </element>
    </sequence>
  </complexType>
  <complexType name="KopidataPropertyType">
    <sequence>
      <element ref="filleveranser:Kopidata"/>
    </sequence>
  </complexType>
  <element name="Posisjonskvalitet" substitutionGroup="gml:AbstractObject" type="filleveranser:PosisjonskvalitetType"/>
  <complexType name="PosisjonskvalitetType">
    <sequence>
      <element name="målemetode" type="gml:CodeType">
        <annotation>
          <appinfo>
            <sc:targetCodeListURI>https://register.geonorge.no/sosi-kodelister/generelle-konsepter/4.5/m%C3%A5lemetodekode</sc:targetCodeListURI>
            <sc:taggedValue tag="SOSI_navn">MÅLEMETODE</sc:taggedValue>
          </appinfo>
        </annotation>
      </element>
    </sequence>
  </complexType>
  <complexType name="PosisjonskvalitetPropertyType">
    <sequence>
      <element ref="filleveranser:Posisjonskvalitet"/>
    </sequence>
  </complexType>
  <simpleType name="SteinBlokkType">
    <union memberTypes="filleveranser:SteinBlokkEnumerationType filleveranser:SteinBlokkOtherType"/>
  </simpleType>
  <simpleType name="SteinBlokkEnumerationType">
    <restriction base="string">
      <enumeration value="Ikke registrert"/>
      <enumeration value="Ingen eller noe stein og blokk"/>
      <enumeration value="Stein og blokkholdig"/>
      <enumeration value="Stein og blokkrik"/>
    </restriction>
  </simpleType>
  <simpleType name="SteinBlokkOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
  <simpleType name="TilleggsinformasjonType">
    <union memberTypes="filleveranser:TilleggsinformasjonEnumerationType filleveranser:TilleggsinformasjonOtherType"/>
  </simpleType>
  <simpleType name="TilleggsinformasjonEnumerationType">
    <restriction base="string">
      <enumeration value="Deler av arealet er bakkeplanert"/>
      <enumeration value="Deler av arealet er forstyrret av graving eller fyllmateriale"/>
      <enumeration value="Ingen"/>
      <enumeration value="Deler av arealet er organisk jord"/>
      <enumeration value="Deler av arealet er preget av vannmetning"/>
      <enumeration value="Deler av arealet er mineraljord"/>
      <enumeration value="Hyppig forekommende fjell i dagen"/>
    </restriction>
  </simpleType>
  <simpleType name="TilleggsinformasjonOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
  <simpleType name="ÅrsakTilNedklassifiseringType">
    <union memberTypes="filleveranser:ÅrsakTilNedklassifiseringEnumerationType filleveranser:ÅrsakTilNedklassifiseringOtherType"/>
  </simpleType>
  <simpleType name="ÅrsakTilNedklassifiseringEnumerationType">
    <restriction base="string">
      <enumeration value="Jordegenskaper"/>
      <enumeration value="Helling"/>
      <enumeration value="Jordegenskaper og helling"/>
      <enumeration value="Hyppig forekommende fjell i dagen"/>
      <enumeration value="Innhold av stein og blokk"/>
      <enumeration value="Deler av arealet har organisk jord, har liten evne til å bli kvitt overflødig vann, er bakkeplanert eller forstyrret av graving eller påfylling"/>
      <enumeration value="Ingen nedklassifisering"/>
    </restriction>
  </simpleType>
  <simpleType name="ÅrsakTilNedklassifiseringOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
</schema>
